import image1 from '../../src/images/grammer.png'
import image2 from '../../src/images/coverly.png'
import image3 from '../../src/images/soberpal.png'
import image4 from '../../src/images/kitchen.png'
import image5 from '../../src/images/street.png'
import image6 from '../../src/images/varena.png'
import image7 from '../../src/images/discripto.png'
import image8 from '../../src/images/magicbook.png'
import image9 from '../../src/images/apply.png'
import image10 from '../../src/images/fixit.png'
import image11 from '../../src/images/vox.png'
import image12 from '../../src/images/devask.png'
import image13 from '../../src/images/catchup.png'
import image14 from '../../src/images/certgo.png'
import image15 from '../../src/images/lovemee.png'
import image16 from '../../src/images/opspad.png'
import image17 from '../../src/images/reconcile.png'
import image18 from '../../src/images/tropical.png'
import image19 from '../../src/images/heed.png'
import icon1 from '../../src/images/arrrow.png'
import icon2 from '../../src/images/arrow.png'




export const props = [
    {
        id: 1,
        image : image1,
        icon: icon1,
        numbergreen:'+4',
        serial: '01' ,
        title: 'Gritty Grammmer',
        text: 'An application that revises grammar problems through discussions with a chat bot that uses AI to transcribe user input',
        customers: '535,000',
        revenue: '$700,000',
        subscribers: '50,000',
        traffic: '2500 daily',
    },
    {
        id: 2,
        image : image2,
        icon: icon1,
        numbergreen:'+3',
        serial: '02' ,
        title: 'Coverly',
        text: 'It is an AI application that gets necessary informations from a CV and generates a Cover letter',
        customers: '535,000',
        revenue: '$700,000',
        subscribers: '50,000',
        traffic: '2500 daily',
    },
    {
        id: 3,
        image : image3,
        icon: icon1,
        numbergreen:'+3',
        serial: '03' ,
        title: 'Soberpal',
        text: 'A to-do list where users can assign tasks to a Virtual Assistant or receive a phone call if they fail to finish a task',
        customers: '535,000',
        revenue: '$700,000',
        subscribers: '50,000',
        traffic: '2500 daily',
    },
    {
        id: 4,
        image : image4,
        icon: icon1,
        numbergreen:'+2',
        serial: '04' ,
        title: 'Kitchen Diary',
        text: 'An application that revises grammar problems through discussions with a chat bot that uses AI to transcribe user input',
        customers: '535,000',
        revenue: '$700,000',
        subscribers: '50,000',
        traffic: '2500 daily',
    },
    {
        id: 5,
        image : image5,
        icon: icon1,
        numbergreen:'+2',
        serial: '05' ,
        title: 'StreetRate',
        text: 'An application that revises grammar problems through discussions with a chat bot that uses AI to transcribe user input',
        customers: '535,000',
        revenue: '$700,000',
        subscribers: '50,000',
        traffic: '2500 daily',
    },
    {
        id: 6,
        image : image6,
        icon: icon1,
        numbergreen:'+1',
        serial: '06' ,
        title: 'V-Arena',
        text: 'An application that revises grammar problems through discussions with a chat bot that uses AI to transcribe user input',
        customers: '535,000',
        revenue: '$700,000',
        subscribers: '50,000',
        traffic: '2500 daily',
    },
    {
        id: 7,
        image : image7,
        icon: icon1,
        numbergreen:'+1',
        serial: '07' ,
        title: 'Discripto',
        text: 'An application that revises grammar problems through discussions with a chat bot that uses AI to transcribe user input',
        customers: '535,000',
        revenue: '$700,000',
        subscribers: '50,000',
        traffic: '2500 daily',
    },
    {
        id: 8,
        image : image8,
        icon: icon1,
        numbergreen:'+1',
        serial: '08' ,
        title: 'Magic Book Writer',
        text: 'An application that revises grammar problems through discussions with a chat bot that uses AI to transcribe user input',
        customers: '535,000',
        revenue: '$700,000',
        subscribers: '50,000',
        traffic: '2500 daily',
    },
    {
        id: 9,
        image : image9,
        icons: icon2,
        numberred:'-1',
        serial: '09' ,
        title: 'Apply For Me',
        text: 'An application that revises grammar problems through discussions with a chat bot that uses AI to transcribe user input',
        customers: '535,000',
        revenue: '$700,000',
        subscribers: '50,000',
        traffic: '2500 daily',
    },
    {
        id: 10,
        image : image10,
        icons: icon2,
        numberred:'-1',
        serial: '10' ,
        title: 'Fixit',
        text: 'An application that revises grammar problems through discussions with a chat bot that uses AI to transcribe user input',
        customers: '535,000',
        revenue: '$700,000',
        subscribers: '50,000',
        traffic: '2500 daily',
    },
    {
        id: 11,
        image : image11,
        icons: icon2,
        numberred:'-2',
        serial: '11' ,
        title: 'Voxclips',
        text: 'An application that revises grammar problems through discussions with a chat bot that uses AI to transcribe user input',
        customers: '535,000',
        revenue: '$700,000',
        subscribers: '50,000',
        traffic: '2500 daily',
    },
    {
        id: 12,
        image : image12,
        icons: icon2,
        numberred:'-2',
        serial: '12' ,
        title: 'Devask',
        text: 'An application that revises grammar problems through discussions with a chat bot that uses AI to transcribe user input',
        customers: '535,000',
        revenue: '$700,000',
        subscribers: '50,000',
        traffic: '2500 daily',
    },
    {
        id: 13,
        image : image13,
        icons: icon2,
        numberred:'-2',
        serial: '13' ,
        title: 'CatchUp',
        text: 'An application that revises grammar problems through discussions with a chat bot that uses AI to transcribe user input',
        customers: '535,000',
        revenue: '$700,000',
        subscribers: '50,000',
        traffic: '2500 daily',
    },
    {
        id: 14,
        image : image14,
        icons: icon2,
        numberred:'-2',
        serial: "14",
        title: 'Certgo',
        text: 'An application that revises grammar problems through discussions with a chat bot that uses AI to transcribe user input',
        customers: '535,000',
        revenue: '$700,000',
        subscribers: '50,000',
        traffic: '2500 daily',
    },
    {
        id: 15,
        image : image15,
        icons: icon2,
        numberred:'-2',
        serial: '15' ,
        title: 'Lovemee',
        text: 'An application that revises grammar problems through discussions with a chat bot that uses AI to transcribe user input',
        customers: '535,000',
        revenue: '$700,000',
        subscribers: '50,000',
        traffic: '2500 daily',
    },
    {
        id: 16,
        image : image16,
        icons: icon2,
        numberred:'-3',
        serial: '16' ,
        title: 'Opspad',
        text: 'An application that revises grammar problems through discussions with a chat bot that uses AI to transcribe user input',
        customers: '535,000',
        revenue: '$700,000',
        subscribers: '50,000',
        traffic: '2500 daily',
    },
    {
        id: 17,
        image : image17,
        icons: icon2,
        numberred:'-3',
        serial: '17' ,
        title: 'ReconcileAi',
        text: 'An application that revises grammar problems through discussions with a chat bot that uses AI to transcribe user input',
        customers: '535,000',
        revenue: '$700,000',
        subscribers: '50,000',
        traffic: '2500 daily',
    },
    {
        id: 18,
        image : image18,
        icons: icon2,
        numberred:'-4',
        serial: '18' ,
        title: 'Tropicalweather',
        text: 'An application that revises grammar problems through discussions with a chat bot that uses AI to transcribe user input',
        customers: '535,000',
        revenue: '$700,000',
        subscribers: '50,000',
        traffic: '2500 daily',
    },
    {
        id: 19,
        image : image19,
        icons: icon2,
        numberred:'-4',
        serial: '19' ,
        title: 'Heed',
        text: 'An application that revises grammar problems through discussions with a chat bot that uses AI to transcribe user input',
        customers: '535,000',
        revenue: '$700,000',
        subscribers: '50,000',
        traffic: '2500 daily',
    },
]